repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        # -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace

    - repo: https://github.com/humitos/mirrors-autoflake.git
      rev: v1.3
      hooks:
        - id: autoflake
          args: ['--in-place', '--expand-star-imports', '--ignore-init-module-imports', '--remove-all-unused-imports']

    -   repo: https://github.com/timothycrosley/isort
        # rev: v4.3.21-2
        rev: e63ae06ec7d70b06df9e528357650281a3d3ec22
        hooks:
        -  id: isort

    -   repo: https://github.com/psf/black
        rev: 19.10b0
        hooks:
        -   id: black
            args: [--line-length=100]
